<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EER3MNQ" failures="1" tests="10" name="Default test" time="40.059" errors="0" timestamp="2021-03-04T00:47:38 ART">
  <testcase classname="testCases.S001LogInCases" name="welcomeisDisplayed" time="0.239">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [WELCOME TO MYXfitness!dsedsf] but found [WELCOME TO MYXfitness!]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [WELCOME TO MYXfitness!dsedsf] but found [WELCOME TO MYXfitness!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testCases.S001LogInCases.welcomeisDisplayed(S001LogInCases.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- welcomeisDisplayed -->
  <testcase classname="testCases.S001LogInCases" name="theRoadisDisplayed" time="0.177"/>
  <testcase classname="testCases.S001LogInCases" name="invalidEmail" time="5.657"/>
  <testcase classname="testCases.S001LogInCases" name="invalidPassword" time="4.388"/>
  <testcase classname="testCases.S001LogInCases" name="noEmailAndPassword" time="3.571"/>
  <testcase classname="testCases.S001LogInCases" name="passwordRecoveryEmpty" time="3.629"/>
  <testcase classname="testCases.S001LogInCases" name="passwordRecoveryWrongEmail" time="7.346"/>
  <testcase classname="testCases.S001LogInCases" name="passwordRecoveryzValid" time="5.591"/>
  <testcase classname="testCases.S001LogInCases" name="iDontHaveAccount" time="2.654"/>
  <testcase classname="testCases.S001LogInCases" name="validEmailAndPassword" time="5.966"/>
</testsuite> <!-- Default test -->
