<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-17T14:46:02 ART" name="Default suite" finished-at="2021-02-17T14:47:57 ART" duration-ms="115128">
    <groups>
    </groups>
    <test started-at="2021-02-17T14:46:02 ART" name="Default test" finished-at="2021-02-17T14:47:57 ART" duration-ms="115128">
      <class name="testCases.HomeMenuCases">
        <test-method is-config="true" signature="startConnection()[pri:0, instance:testCases.HomeMenuCases@566d0c69]" started-at="2021-02-17T14:45:53 ART" name="startConnection" finished-at="2021-02-17T14:46:02 ART" duration-ms="8873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startConnection -->
        <test-method signature="openMenu()[pri:0, instance:testCases.HomeMenuCases@566d0c69]" started-at="2021-02-17T14:46:02 ART" name="openMenu" description="Open Menu functionality" finished-at="2021-02-17T14:46:04 ART" duration-ms="1690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openMenu -->
        <test-method signature="openManageProfiles()[pri:1, instance:testCases.HomeMenuCases@566d0c69]" started-at="2021-02-17T14:46:04 ART" name="openManageProfiles" description="Open Manage Profiles" finished-at="2021-02-17T14:46:14 ART" duration-ms="10012" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openManageProfiles -->
        <test-method signature="editManageProfiles()[pri:2, instance:testCases.HomeMenuCases@566d0c69]" started-at="2021-02-17T14:46:14 ART" name="editManageProfiles" description="Edit Manage Profiles" finished-at="2021-02-17T14:47:01 ART" duration-ms="47611" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testCases.HomeMenuCases.editManageProfiles(HomeMenuCases.java:192)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editManageProfiles -->
        <test-method signature="editManageProfilesBack()[pri:3, instance:testCases.HomeMenuCases@566d0c69]" started-at="2021-02-17T14:47:01 ART" name="editManageProfilesBack" description="Edit Manage Profiles" finished-at="2021-02-17T14:47:57 ART" duration-ms="55636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editManageProfilesBack -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testCases.HomeMenuCases@566d0c69]" started-at="2021-02-17T14:47:57 ART" name="TearDown" finished-at="2021-02-17T14:47:57 ART" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- testCases.HomeMenuCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
